services:
  zookeeper:
    image: bitnamilegacy/zookeeper:3.8.1
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - cqrs_docker_network

  kafka:
    image: bitnamilegacy/kafka:3.6.2   # or public.ecr.aws/bitnami/kafka:latest  or bitnamicharts/kafka:32.4.3 
    container_name: kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_LISTENERS=PLAINTEXT://:9092
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    networks:
      - cqrs_docker_network
    depends_on:
      - zookeeper

  mongo:
    image: mongo:latest
    container_name: mongo-container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - cqrs_docker_network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'admin'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'password'
      ME_CONFIG_MONGODB_SERVER: 'mongo'
    networks:
      - cqrs_docker_network
    depends_on: 
      -  mongo
  
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-container
    restart: always
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Str0ngS@P@ssw0rd02'
      MSSQL_PID: 'Express'
    networks:
      - cqrs_docker_network

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - cqrs_docker_network

#  mysql:
#    image: mysql:8.0
#    container_name: mysql
#    restart: always
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql-db:/var/lib/mysql
#    environment:
#      MYSQL_DATABASE: 'DB'
#      # So you don't have to use root, but you can if you like
#      MYSQL_USER: 'user'
#      # You can use whatever password you like
#      MYSQL_PASSWORD: 'password'
#      # Password for root access
#      MYSQL_ROOT_PASSWORD: 'password'
#    networks:
#      - cqrs_docker_network

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongodb_data:
    driver: local
  mysql-db:
    driver: local
  pg_data:
    driver: local
    
    
networks:
  cqrs_docker_network:
    driver: bridge
    
#networks:
#  default:
#    name: mydockernetwork
#    external: true